# Generated by Django 4.2.1 on 2023-05-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PetType", models.CharField(max_length=10)),
                ("Breed", models.CharField(max_length=10)),
                ("PhotoPet", models.FileField(upload_to="")),
                ("SpecialCare", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ProductType", models.CharField(max_length=10)),
                ("PetType", models.CharField(max_length=10)),
                ("PhotoProd", models.FileField(upload_to="")),
                ("Size", models.CharField(max_length=10)),
                ("Quantity", models.CharField(max_length=10)),
            ],
        ),
    ]
