# Generated by Django 4.2.1 on 2023-05-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zootopia", "0003_alter_pets_petname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pets",
            name="PhotoPet",
            field=models.ImageField(upload_to="images"),
        ),
    ]
