# Generated by Django 4.2.1 on 2023-05-26 07:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zootopia", "0005_register"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Register",
            new_name="Register_User",
        ),
    ]
