# Generated by Django 4.2.1 on 2023-05-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zootopia", "0006_rename_register_register_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="register_user",
            name="role",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register_user",
            name="status",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="register_user",
            name="Gender",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="register_user",
            name="Name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="register_user",
            name="Password1",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="register_user",
            name="Password2",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="register_user",
            name="Username",
            field=models.CharField(max_length=20),
        ),
    ]
