# Generated by Django 4.2.1 on 2023-05-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zootopia", "0007_register_user_role_register_user_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pets",
            name="Price",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
