# Generated by Django 4.2.1 on 2023-05-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zootopia", "0010_remove_pets_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="pets",
            name="Status",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
