# Generated by Django 4.2.1 on 2023-05-29 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zootopia", "0012_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="pet",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="zootopia.pets",
            ),
            preserve_default=False,
        ),
    ]
