# Generated by Django 4.2.1 on 2023-05-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zootopia", "0014_rename_pet_cart_pets"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="PetS",
            new_name="Pets",
        ),
    ]
