# Generated by Django 4.2.1 on 2023-05-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zootopia", "0017_rename_productname_pay_petsname"),
    ]

    operations = [
        migrations.AddField(
            model_name="pay",
            name="cart_status",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
