# Generated by Django 4.2.1 on 2023-05-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zootopia", "0019_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
