# Generated by Django 4.2.1 on 2023-05-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zootopia", "0021_remove_cart_total_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="Pets",
        ),
    ]
