# Generated by Django 4.2.1 on 2023-05-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zootopia", "0022_remove_order_pets"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="Price",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
