# Generated by Django 4.2.1 on 2023-05-30 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zootopia", "0023_products_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="Products",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="zootopia.products",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="Pets",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="zootopia.pets",
            ),
        ),
    ]
