# Generated by Django 4.2.1 on 2023-05-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zootopia", "0029_alter_cart_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="Products",
        ),
    ]
