# Generated by Django 4.2.1 on 2023-05-31 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zootopia", "0031_alter_cart_pets"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="Products",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="zootopia.products",
            ),
            preserve_default=False,
        ),
    ]
